<a href="https://colab.research.google.com/github/timonpalm/TFCourse/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A Notebook about the most fundamental concepts using Tensorflow

More specifically:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensor & NumPy
* Using @tf.function (a way to speed up my regular Python functions)
* Using GPUs with TensorFlow (or TPUs)

## Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
 # Chech the number of dimensions of a tensor
 scalar.ndim

0

In [7]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
# Check the dimension of the vector
vector.ndim

1

In [9]:
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [7.,10.],
                              [1.,2.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 1.,  2.]], dtype=float16)>

In [12]:
# What's the number of dimensions of another_matrix?
another_matrix.ndim

2

In [13]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [16]:
tensor.ndim

3